//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Assessment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer_table
    {
        public int Answer_Id { get; set; }
        public int Test_Id { get; set; }
        public int User_Id { get; set; }
        public int Question_Id { get; set; }
        public int Option_Id { get; set; }
        public System.DateTime Submit_date { get; set; }
    
        public virtual Option_table Option_table { get; set; }
        public virtual Question_table Question_table { get; set; }
        public virtual Test_table Test_table { get; set; }
        public virtual User_table User_table { get; set; }
    }
}
