//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Assessment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option_table
    {
        public Option_table()
        {
            this.Answer_table = new HashSet<Answer_table>();
        }
    
        public int Option_Id { get; set; }
        public int Question_Id { get; set; }
        public string Options { get; set; }
        public bool Answer { get; set; }
    
        public virtual ICollection<Answer_table> Answer_table { get; set; }
        public virtual Question_table Question_table { get; set; }
    }
}
