//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Assessment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question_mapping_table
    {
        public int Question_map_id { get; set; }
        public int Test_Id { get; set; }
        public int Question_Id { get; set; }
    
        public virtual Question_table Question_table { get; set; }
        public virtual Test_table Test_table { get; set; }
    }
}
