//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Assessment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question_table
    {
        public Question_table()
        {
            this.Answer_table = new HashSet<Answer_table>();
            this.Option_table = new HashSet<Option_table>();
            this.Question_mapping_table = new HashSet<Question_mapping_table>();
        }
    
        public int Question_Id { get; set; }
        public int Subject_id { get; set; }
        public string Questions { get; set; }
        public int Difficulty_Id { get; set; }
    
        public virtual ICollection<Answer_table> Answer_table { get; set; }
        public virtual Difficulty_table Difficulty_table { get; set; }
        public virtual ICollection<Option_table> Option_table { get; set; }
        public virtual ICollection<Question_mapping_table> Question_mapping_table { get; set; }
        public virtual Subject_table Subject_table { get; set; }
    }
}
