//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Assessment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject_table
    {
        public Subject_table()
        {
            this.Question_table = new HashSet<Question_table>();
        }
    
        public int Subject_Id { get; set; }
        public string Subject_name { get; set; }
    
        public virtual ICollection<Question_table> Question_table { get; set; }
    }
}
