//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Assessment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_invitation_table
    {
        public int Invitation_Id { get; set; }
        public int Test_Id { get; set; }
        public string User_email { get; set; }
        public System.DateTime Invited_date { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Result { get; set; }
    
        public virtual Test_table Test_table { get; set; }
    }
}
